# Generated by Django 5.1.6 on 2025-03-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='execution_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_in_usd',
        ),
    ]
