# Generated by Django 5.1.6 on 2025-03-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='seller',
        ),
    ]
