# Generated by Django 5.1.6 on 2025-03-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='execution_type',
            field=models.CharField(choices=[('limit_order', 'Limit_order'), ('market_order', 'Market_order')], default='limit_order', max_length=20),
        ),
    ]
