# Generated by Django 5.1.6 on 2025-03-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_remove_trade_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_declined',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wallet',
        ),
        migrations.AddField(
            model_name='order',
            name='external_order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_in_usdt',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='order',
            name='trade_fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='external_pair_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
