# Generated by Django 5.1.6 on 2025-03-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_order_execution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='execution_type',
            field=models.CharField(choices=[('limit', 'Limit'), ('market', 'Market')], default='limit_order', max_length=20),
        ),
    ]
