# Generated by Django 5.1.6 on 2025-03-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_order_is_approved'),
        ('trading', '0005_auto_20250312_1457'),
    ]

    operations = [
    ]
