# Generated by Django 5.1.6 on 2025-03-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_merge_0004_order_is_approved_0005_auto_20250312_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
