# Generated by Django 5.1.6 on 2025-03-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_order_is_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='order',
            name='total_in_usd',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='execution_type',
            field=models.CharField(choices=[('limit', 'Limit'), ('market', 'Market')], default='limit', max_length=20),
        ),
    ]
