# Generated by Django 5.1.6 on 2025-02-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('id_pk', models.CharField(max_length=50, unique=True)),
                ('is_tradable', models.BooleanField(default=True)),
                ('crypto_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('network_description', models.CharField(blank=True, max_length=200, null=True)),
                ('acronym', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
