# Generated by Django 5.1.6 on 2025-03-03 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_currency', '0002_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
