# Generated by Django 5.1.6 on 2025-03-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_currency', '0003_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
