# Generated by Django 5.1.6 on 2025-03-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_currency', '0005_cryptocurrency_last_updated_cryptocurrency_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='logo_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
