# Generated by Django 5.1.6 on 2025-03-04 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_currency', '0006_cryptocurrency_logo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='network',
            name='logo_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CryptocurrencyNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deposit_enabled', models.BooleanField(default=True)),
                ('is_withdrawal_enabled', models.BooleanField(default=True)),
                ('withdrawal_fee', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('min_withdrawal', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('deposit_confirmations', models.IntegerField(default=6)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='crypto_currency.cryptocurrency')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_currency.network')),
            ],
            options={
                'unique_together': {('cryptocurrency', 'network')},
            },
        ),
    ]
