# Generated by Django 5.1.6 on 2025-03-09 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_currency', '0007_network_is_active_network_logo_path_and_more'),
        ('user_account', '0008_alter_userdetail_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_timeframe', models.CharField(default='24h', max_length=10)),
                ('show_volume', models.BooleanField(default=True)),
                ('chart_type', models.CharField(default='line', max_length=20)),
            ],
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['cryptocurrency', 'timestamp'], name='crypto_curr_cryptoc_2603d0_idx'),
        ),
        migrations.AddField(
            model_name='chartpreference',
            name='cryptocurrency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_currency.cryptocurrency'),
        ),
        migrations.AddField(
            model_name='chartpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_preferences', to='user_account.user'),
        ),
        migrations.AlterUniqueTogether(
            name='chartpreference',
            unique_together={('user', 'cryptocurrency')},
        ),
    ]
