# Generated by Django 5.1.6 on 2025-02-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_role_knowyourcustomer_userdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='role_id',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='role_id',
            field=models.ManyToManyField(blank=True, null=True, to='user_account.role'),
        ),
    ]
