# Generated by Django 5.1.6 on 2025-02-26 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_remove_userdetail_role_id_userdetail_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_account.user'),
        ),
    ]
