# Generated by Django 5.1.6 on 2025-03-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_address_useraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role_name',
            new_name='role',
        ),
    ]
