# Generated by Django 5.1.6 on 2025-03-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_rename_role_name_role_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='user_profile',
            field=models.ImageField(blank=True, upload_to='user_profile/'),
        ),
    ]
