# Generated by Django 5.1.6 on 2025-03-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_userdetail_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
