# Generated by Django 5.1.6 on 2025-03-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0008_alter_userdetail_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowyourcustomer',
            name='back_captured_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowyourcustomer',
            name='captured_selfie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowyourcustomer',
            name='front_captured_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
