# Generated by Django 5.1.6 on 2025-03-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0009_knowyourcustomer_back_captured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='role_id',
        ),
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.ManyToManyField(blank=True, null=True, to='user_account.role'),
        ),
    ]
