# Generated by Django 5.1.6 on 2025-03-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0011_userdetail_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
