# Generated by Django 5.1.6 on 2025-03-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0012_user_jwt_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='secret_phrase',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='uid',
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_phrase',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
