# Generated by Django 5.1.6 on 2025-03-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0013_remove_userdetail_referral_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
