# Generated by Django 5.1.6 on 2025-03-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0014_alter_userdetail_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='ip_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
