# Generated by Django 5.1.6 on 2025-05-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0015_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='user_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
