# Generated by Django 5.1.6 on 2025-06-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0016_userdetail_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
