# Generated by Django 5.1.6 on 2025-06-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0017_alter_userdetail_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='previous_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
