# Generated by Django 5.1.6 on 2025-06-17 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0018_alter_userdetail_previous_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyourcustomer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.user'),
        ),
    ]
