# Generated by Django 5.1.6 on 2025-02-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_alter_userdetail_user_id'),
        ('wallet', '0002_walletaddress_network_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user_id',
        ),
        migrations.AddField(
            model_name='wallet',
            name='user_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_wallet', to='user_account.user'),
        ),
    ]
