# Generated by Django 5.1.6 on 2025-02-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_currency', '0001_initial'),
        ('wallet', '0003_remove_wallet_user_id_wallet_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='wallet_id',
        ),
        migrations.RemoveField(
            model_name='walletaddress',
            name='network_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='transactions', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='walletaddress',
            name='network_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='wallet_addresses', to='crypto_currency.network'),
        ),
    ]
