# Generated by Django 5.1.6 on 2025-02-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_currency', '0001_initial'),
        ('wallet', '0005_walletbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletbalance',
            name='cryptocurrency',
        ),
        migrations.AddField(
            model_name='walletbalance',
            name='cryptocurrency',
            field=models.ManyToManyField(blank=True, null=True, related_name='crypto_currency', to='crypto_currency.cryptocurrency'),
        ),
    ]
