# Generated by Django 5.1.6 on 2025-02-27 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_currency', '0001_initial'),
        ('wallet', '0006_remove_walletbalance_cryptocurrency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletbalance',
            name='wallet',
        ),
        migrations.AddField(
            model_name='walletbalance',
            name='wallet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='wallet.wallet'),
        ),
        migrations.RemoveField(
            model_name='walletbalance',
            name='cryptocurrency',
        ),
        migrations.AddField(
            model_name='walletbalance',
            name='cryptocurrency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crypto_currency.cryptocurrency'),
        ),
    ]
