# Generated by Django 5.1.6 on 2025-02-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_remove_walletbalance_wallet_walletbalance_wallet_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletbalance',
            old_name='wallet_id',
            new_name='wallet',
        ),
    ]
