# Generated by Django 5.1.6 on 2025-02-28 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_currency', '0001_initial'),
        ('wallet', '0008_rename_wallet_id_walletbalance_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletbalance',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_network', to='crypto_currency.cryptocurrency'),
        ),
    ]
