# Generated by Django 5.1.6 on 2025-03-03 06:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_currency', '0003_delete_address'),
        ('user_account', '0005_address_useraddress'),
        ('wallet', '0009_walletbalance_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='walletaddress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='walletbalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('transfer', 'Transfer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_id',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user_id',
            field=models.ManyToManyField(blank=True, related_name='user_wallet', to='user_account.user'),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='network_id',
            field=models.ManyToManyField(blank=True, related_name='wallet_addresses', to='crypto_currency.network'),
        ),
        migrations.AlterField(
            model_name='walletbalance',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_network', to='crypto_currency.network'),
        ),
    ]
