# Generated by Django 5.1.6 on 2025-03-03 07:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_currency', '0003_delete_address'),
        ('wallet', '0010_transaction_destination_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cryptocurrency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crypto_currency.cryptocurrency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crypto_currency.network'),
        ),
        migrations.AddField(
            model_name='walletaddress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='walletaddress',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='walletbalance',
            name='last_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affected_balances', to='wallet.transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='walletbalance',
            unique_together={('wallet', 'cryptocurrency', 'network')},
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=24)),
                ('change_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_currency.cryptocurrency')),
            ],
        ),
    ]
