# Generated by Django 5.1.6 on 2025-03-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_currency', '0007_network_is_active_network_logo_path_and_more'),
        ('wallet', '0012_transaction_confirmation_count_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WalletBalance',
            new_name='UserAsset',
        ),
    ]
